"""SDOL type definitions."""

from sdol.types.capability import (
    ConnectorCapabilities,
    ConnectorCapability,
    ConnectorPerformance,
)
from sdol.types.connector import ConnectorHealth, ConnectorResult, ConnectorResultMeta
from sdol.types.context import (
    ContextConflict,
    ContextElement,
    ContextFrame,
    ContextFrameStats,
    ContextSlot,
    ContextSlotType,
    ConflictResolution,
)
from sdol.types.errors import (
    ConnectorTimeoutError,
    InvalidIntentError,
    MCPTransportError,
    NoCapableConnectorError,
    SDOLError,
    SDOLErrorCode,
)
from sdol.types.intent import (
    AggregateAnalysisIntent,
    BaseIntent,
    CompositeIntent,
    EscapeHatchIntent,
    FilterClause,
    FusionOperator,
    GraphTraversalIntent,
    Intent,
    IntentType,
    MeasureSpec,
    NodeSpec,
    OntologyQueryIntent,
    OrderSpec,
    PointLookupIntent,
    SemanticSearchIntent,
    TemporalTrendIntent,
    TimeWindow,
    validate_intent,
)
from sdol.types.provenance import (
    ConsistencyGuarantee,
    PrecisionClass,
    ProvenanceEnvelope,
    RetrievalMethod,
    TrustDimensions,
    TrustScore,
)
from sdol.types.router import (
    ExecutionError,
    ExecutionPlan,
    ExecutionResult,
    ExecutionStep,
)

__all__ = [
    "AggregateAnalysisIntent",
    "BaseIntent",
    "CompositeIntent",
    "ConflictResolution",
    "ConnectorCapabilities",
    "ConnectorCapability",
    "ConnectorHealth",
    "ConnectorPerformance",
    "ConnectorResult",
    "ConnectorResultMeta",
    "ConnectorTimeoutError",
    "ConsistencyGuarantee",
    "ContextConflict",
    "ContextElement",
    "ContextFrame",
    "ContextFrameStats",
    "ContextSlot",
    "ContextSlotType",
    "EscapeHatchIntent",
    "ExecutionError",
    "ExecutionPlan",
    "ExecutionResult",
    "ExecutionStep",
    "FilterClause",
    "FusionOperator",
    "GraphTraversalIntent",
    "Intent",
    "IntentType",
    "InvalidIntentError",
    "MCPTransportError",
    "MeasureSpec",
    "NoCapableConnectorError",
    "NodeSpec",
    "OntologyQueryIntent",
    "OrderSpec",
    "PointLookupIntent",
    "PrecisionClass",
    "ProvenanceEnvelope",
    "RetrievalMethod",
    "SDOLError",
    "SDOLErrorCode",
    "SemanticSearchIntent",
    "TemporalTrendIntent",
    "TimeWindow",
    "TrustDimensions",
    "TrustScore",
    "validate_intent",
]
